import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'
import { ThemeProvider } from '@/provider/theme-provider'
import { cn } from '@/lib/utils'
import { Navbar, NavigationHelper } from '@/components/custom'
import './globals.css'
import './global-icons.css'
import {
  AuthDialog,
  JobCreateDialog,
  PostCreateDialog
} from '@/components/custom/global-dialog'
const inter = Open_Sans({ subsets: ['cyrillic'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children,
  modal
}: Readonly<{
  children: React.ReactNode
  modal: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={cn(inter.className, 'bg-darkAccent')}>
        <ThemeProvider
          attribute='class'
          defaultTheme='dark'
          enableSystem
          disableTransitionOnChange
        >
          <Navbar className='h-16' />
          <div className='h-[calc(100%-64px)] overflow-y-auto scroller'>
            {children}
            {modal}
          </div>
          {/* <AuthDialog />
          <PostCreateDialog />
          <JobCreateDialog /> */}
          <NavigationHelper />
        </ThemeProvider>
      </body>
    </html>
  )
}
